[WIP] Read Iceberg to DeltacatDataset
ray-project/deltacat pull request #131
Opened 2023-05-10 16:37 UTC by JonasJ-ap

Adds a `read_iceberg` read API, which uses [`pyiceberg`](https://github.com/apache/iceberg/tree/master/python/pyiceberg) and Ray Data API `read_parquet`.

Waiting for `pyiceberg0.4.0" Release (Release Vote Begins)

2023-05-10 16:40 UTC, JonasJ-ap commented on setup.py
> -        "s3fs == 2022.2.0",
`pyiceberg 0.3.0` requires `2023.1.0` in its specification. The version range will be widen in the next release (0.4.0)

2023-06-25 02:09 UTC, pdames requested changes
As a high-level comment, let's (1) target merging this into a new `iceberg` branch instead of the `main` branch for now and (2) ensure that all changes pass the linter by following the steps  at https://github.com/ray-project/deltacat/blob/main/README-development.md. You can also review the complete set of suggested changes here that are passing `make test-integration` on my Macbook at https://github.com/pdames/deltacat/tree/add_read_iceberg.

2023-06-27 22:32 UTC, JonasJ-ap reviewed
@pdames Thank you for your review and suggestions. I've incorporated your suggested update and revised the integration test structure.

2023-06-28 02:25 UTC, pdames commented
LGTM - nice work @JonasJ-ap!

2023-06-28 02:26 UTC, merged